### PR TITLE
Moving power manifold to base

### PR DESCRIPTION
**Pull request by mateuszbaran**
Will solve https://github.com/JuliaManifolds/ManifoldsBase.jl/issues/54 . Has a counterpart in Manifolds.jl: https://github.com/JuliaManifolds/Manifolds.jl/pull/274 .

### CODE REVIEW

**Comment by kellertuer** [comment]
Thanks, I will start this soon, great that nearly all of the methods seem to be able to move. The fist test indicates you might have accidentially moved a flat function?

**Comment by mateuszbaran** [comment]
Yes, I've moved a bit too many. I've moved some back in the second commit.

**Comment by kellertuer** [comment]
Thanks for this great start, currently this introduces 2 ambiguities in `get_vector`s and `get_coordinates`s `allocate_result` with respect to the `CachedBasis`. I tried to fix that, but was not yet able to.

**Comment by kellertuer** [comment]
It's still some work to do, and we have to adapt the docs a little bit, since I also moved Error types and a `size_to_tuple` internal function; but then the `Interface.html` will just also get an internal functions part, once this is finished and we finish the corresponding branch over on Manifolds.

All in all I feel like this is a very good idea to introduce this here.

**Comment by mateuszbaran** [comment]
Hmm.. I think the remaining coverage failures are false positives.

**Comment by kellertuer** [comment]
Thanks for the help. I will check tomorrow whether we can get the codecovs to succeed by finding one line, that's all what might be missing to stay in the same range as before.

**Comment by kellertuer** [comment]
I checked and you are right, the remaining ones seem to be false misses.

**Comment by kellertuer** [comment]
Since this is breaking it would be the version 0.10.0? I am fine with this version, especially since locally the other branch works. Also: Should we geht a DOI here, too?

**Comment by mateuszbaran** [comment]
Yes, it looks like it should be 0.10.

I don't think we need a DOI for ManifoldsBase.jl.

**Comment by kellertuer** [comment]
I also think we do not necessarily need one, but on the other hand it would also just work automatically. Well we can add it also, when we find it necessary (and usually one would use the one of Manifolds.jl anyways then I think).

**Pull request merged**
