### PR TITLE
Fix `number_of_coordinates` on embedded manifolds

### PR DESCRIPTION
**Pull request by mateuszbaran**
https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/85 incorrectly made `number_of_coordinates` transparent for embedded manifolds, and this fixes the problem.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
@kellertuer This fixed some problems but the complex variant of `SkewHermitianMatrices` is still failing:
```julia
Type Matrix{ComplexF64}: Error During Test at /home/mateusz/.julia/dev/Manifolds/test/manifolds/skewhermitian.jl:86
  Got exception outside of a @test
  AssertionError: size(Y) == (dim,)
  Stacktrace:
    [1] get_coordinates!(M::SkewHermitianMatrices{3, ℂ}, Y::Vector{ComplexF64}, p::Matrix{ComplexF64}, X::Matrix{ComplexF64}, #unused#::DefaultOrthonormalBasis{ℂ, ManifoldsBase.TangentSpaceType})
      @ Manifolds ~/.julia/dev/Manifolds/src/manifolds/SkewHermitian.jl:122
    [2] get_coordinates
      @ ~/.julia/dev/ManifoldsBase/src/bases.jl:486 [inlined]
    [3] get_coordinates__parent
      @ ~/.julia/dev/ManifoldsBase/src/DecoratorManifold.jl:427 [inlined]
    [4] get_coordinates
      @ ~/.julia/dev/ManifoldsBase/src/DecoratorManifold.jl:390 [inlined]
    [5] test_manifold(M::SkewHermitianMatrices{3, ℂ}, pts::Vector{Matrix{ComplexF64}}; basis_has_specialized_diagonalizing_get::Bool, basis_types_to_from::Tuple{DefaultOrthonormalBasis{ℂ, ManifoldsBase.TangentSpaceType}}, basis_types_vecs::Tuple{DefaultOrthonormalBasis{ℂ, ManifoldsBase.TangentSpaceType}}, default_inverse_retraction_method::LogarithmicInverseRetraction, default_retraction_method::ExponentialRetraction, exp_log_atol_multiplier::Int64, exp_log_rtol_multiplier::Int64, expected_dimension_type::Type, inverse_retraction_methods::Vector{Any}, is_mutating::Bool, is_point_atol_multiplier::Int64, is_tangent_atol_multiplier::Int64, musical_isomorphism_bases::Vector{Any}, point_distributions::Vector{Any}, projection_atol_multiplier::Int64, rand_tvector_atol_multiplier::Int64, retraction_atol_multiplier::Int64, retraction_methods::Vector{Any}, retraction_rtol_multiplier::Int64, test_atlases::Tuple{}, test_exp_log::Bool, test_forward_diff::Bool, test_is_tangent::Bool, test_injectivity_radius::Bool, test_inplace::Bool, test_musical_isomorphisms::Bool, test_mutating_rand::Bool, test_project_point::Bool, test_project_tangent::Bool, test_representation_size::Bool, test_reverse_diff::Bool, test_riesz_representer::Bool, test_tangent_vector_broadcasting::Bool, test_default_vector_transport::Bool, test_vector_spaces::Bool, test_vee_hat::Bool, tvector_distributions::Vector{Any}, vector_transport_methods::Vector{Any}, vector_transport_inverse_retractions::Vector{LogarithmicInverseRetraction}, vector_transport_retractions::Vector{ExponentialRetraction}, test_vector_transport_to::Vector{Bool}, test_vector_transport_direction::Vector{Bool}, mid_point12::Matrix{ComplexF64})
      @ Manifolds ~/.julia/dev/Manifolds/src/tests/tests_general.jl:582
    [6] macro expansion
      @ ~/.julia/dev/Manifolds/test/manifolds/skewhermitian.jl:87 [inlined]
```
Do you know how to fix that or should I just go back to overloading `number_of_coordinates` for `CircleGroup`?

**Comment by mateuszbaran** [comment]
I think I'm going to revert https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/85 , this issue blocks further work on https://github.com/JuliaManifolds/Manifolds.jl/pull/416 and I don't really want to spend more time figuring out how to fix this when there is a very simple workaround.

**Comment by kellertuer** [comment]
Sorry I have not yet had a chance to take a look for the newest error; I think #85 would be the right way to do it and we somehow missed to do that (and do it correctly for EmbeddedManifolds). But it is again very very tricky and I would have to invest more time (which I do not have this week). So, if we just fix it in manifolds.jl for now that's ok with me.

**Comment by kellertuer** [comment]
Hm we never merged this, did we resolve this issue with the new interface?

**Comment by mateuszbaran** [comment]
I'm not sure but it's either fixed or requires a completely different fix so this needs to be closed anyway.

**Pull request closed without merging**
