### PR TITLE
Allocations with no points default to `Array`s of `Float64`

### PR DESCRIPTION
**Pull request by mateuszbaran**
Needed for second part of https://github.com/JuliaManifolds/Manifolds.jl/pull/450 , that is random points without array as an "example".

### CODE REVIEW

**Comment by kellertuer** [comment]
I do not See that directly, but why can this not happen (the ambiguity)?

**Comment by kellertuer** [comment]
Besides my question above, this looks like really good defaults to introduce, so with me getting the detail why this can't happen – I would be fine merging this :)

**Comment by mateuszbaran** [comment]
> I do not See that directly, but why can this not happen (the ambiguity)?

You'd have to call `allocate_result(M, get_coordinates)` for example, and every time you get coordinates you have some point that you can put as an argument there. It could only happen if there was a valid way to call `get_vector` or `get_coordinates` without any points, coordinates or vectors.

**Comment by kellertuer** [comment]
Ah, thanks for the explanations. You are right, this is a case that should not happen if using allocate correctly. So then, this looks fine to me.

**Review by kellertuer — APPROVED** [review]

**Pull request merged**
