### PR TITLE
Resolve some basis-related ambiguities

### PR DESCRIPTION
**Pull request by mateuszbaran**
This resolves some ambiguities detected in Manifolds.jl tests.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
There is also a small issue that some methods of `vector_transport_along` require `c::AbstractVector` while other do not. We should probably decide one way or the other.

**Comment by kellertuer** [comment]
I think I would opt for putting the AbstractVector, what do you think?

**Comment by mateuszbaran** [comment]
OK, I'll add `AbstractVector` then.

I have no idea why we lost coverage though.

**Comment by kellertuer** [comment]
Uh now we even lost 10 lines, hm. We might have to check that, then; I can try to find time, but only on Friday.

**Comment by mateuszbaran** [comment]
I'll take a look at it, at least things related to vector transport could be real.

**Comment by mateuszbaran** [comment]
Hm, we don't have some generic `DifferentiatedRetractionVectorTransport` methods but no concrete implementation. I'm not sure why it didn't show up earlier in coverage.

**Comment by mateuszbaran** [comment]
Coverage if full now, I think this can be merged.

**Comment by kellertuer** [comment]
Looking forward to seeing the effect on Manifolds :)

**Review by kellertuer — APPROVED** [review]

**Pull request merged**
