### PR TITLE
Don't inline `invoke` in a generic fallback.

### PR DESCRIPTION
**Pull request by mateuszbaran**
Workaround for https://discourse.julialang.org/t/extremely-slow-invoke-when-inlined/90665 .

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I will tag 0.13.26 after merging this.

**Comment by mateuszbaran** [comment]
Ref. https://github.com/JuliaLang/julia/pull/47671

**Comment by kellertuer** [comment]
Nice! You even managed to get an update to Julia with that. Super!

**Review by kellertuer — APPROVED** [review]

**Comment by mateuszbaran** [comment]
CI keeps failing on Julia 1.0/macOS without a clear error message :confused: .

**Comment by kellertuer** [comment]
How general where `Varargs` possible in Julia 1.0?

**Comment by mateuszbaran** [comment]
Since the code works on Ubuntu and the Vararg change passed CI earlier, I'd say that it's certainly not the issue here.

**Comment by kellertuer** [comment]
Oh, yes, I did not notice that; hm, to me the message looks a little bit like Pkg not being able to get the package, at least on windows I had a similar message once that vanished after a while.

**Pull request merged**
